import {
  Ambulance,
  Calendar,
  ArrowRight,
  Bike,
  Bot,
  Brain,
  Camera,
  ChartColumn,
  ChartPie,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  ClipboardPlus,
  Expand,
  FileText,
  Fingerprint,
  GitBranch,
  Headset,
  History,
  Timer,
  PhoneOff,
  HouseWifi,
  IdCard,
  Info,
  Keyboard,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  LocateFixed,
  Lock,
  LogOut,
  MapPin,
  MapPinned,
  Mic,
  Moon,
  Navigation,
  PhoneCall,
  Power,
  Radio,
  Satellite,
  SatelliteDish,
  Scale,
  Server,
  ShieldHalf,
  SkipForward,
  Smartphone,
  Stethoscope,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  VenetianMask,
  Video,
  Volume2,
  VolumeX,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Ícones Lucide (padrão Samais: stroke 1.5, tamanho em 1em — herda o
 * font-size do contexto, como os antigos <i> de webfont).
 * Nomes mantêm o vocabulário Font Awesome usado historicamente no App
 * para a migração ser mecânica e o diff legível.
 */
const ICONS: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  'arrow-right-from-bracket': LogOut,
  'arrow-trend-down': TrendingDown,
  'arrow-trend-up': TrendingUp,
  bolt: Zap,
  brain: Brain,
  calendar: Calendar,
  camera: Camera,
  'chart-pie': ChartPie,
  'chart-simple': ChartColumn,
  'check-double': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-info': Info,
  'circle-notch': LoaderCircle,
  'clock-rotate-left': History,
  stopwatch: Timer,
  'code-branch': GitBranch,
  expand: Expand,
  'file-lines': FileText,
  'file-medical': ClipboardPlus,
  'file-pdf': FileText,
  fingerprint: Fingerprint,
  'forward-step': SkipForward,
  headset: Headset,
  'house-signal': HouseWifi,
  'id-badge': IdCard,
  keyboard: Keyboard,
  'list-check': ListChecks,
  'list-ol': ListOrdered,
  'location-arrow': Navigation,
  'location-crosshairs': LocateFixed,
  'location-dot': MapPin,
  lock: Lock,
  'map-location-dot': MapPinned,
  mask: VenetianMask,
  'microphone-lines': Mic,
  'mobile-screen': Smartphone,
  moon: Moon,
  motorcycle: Bike,
  'phone-volume': PhoneCall,
  'phone-slash': PhoneOff,
  'power-off': Power,
  robot: Bot,
  satellite: Satellite,
  'satellite-dish': SatelliteDish,
  'scale-unbalanced': Scale,
  server: Server,
  'shield-halved': ShieldHalf,
  stethoscope: Stethoscope,
  'triangle-exclamation': TriangleAlert,
  'truck-fast': Truck,
  'truck-medical': Ambulance,
  user: User,
  'user-doctor': Stethoscope,
  video: Video,
  'volume-high': Volume2,
  'volume-xmark': VolumeX,
  'walkie-talkie': Radio,
};

export type IconName = keyof typeof ICONS;

export function Icon({ name, className }: { name: string; className?: string }) {
  const C = ICONS[name];
  if (!C) return null;
  return (
    <C
      aria-hidden="true"
      size="1em"
      strokeWidth={1.5}
      className={className ? `inline-block align-[-0.125em] shrink-0 ${className}` : 'inline-block align-[-0.125em] shrink-0'}
    />
  );
}
